from PySide6.QtCore import Qt, QSize, QDate, QRect, QMetaObject, QCoreApplication
from PySide6.QtGui import QCursor, QAction
from PySide6.QtWidgets import QSizePolicy, QWidget, QGridLayout, QComboBox, QDateEdit, QDateTimeEdit, QFrame, QTableWidget, QSpacerItem, QPushButton, QAbstractScrollArea, QAbstractItemView, QMenuBar, QMenu, QStatusBar


class Ui_MainWindow(object): 
    def setupUi(self, MainWindow): 
        if not MainWindow.objectName(): 
            MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1114, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setCursor(QCursor(Qt.ArrowCursor))
        MainWindow.setStyleSheet("")
        self.addRoom = QAction(MainWindow)
        self.addRoom.setObjectName("addRoom")
        self.removeRoom = QAction(MainWindow)
        self.removeRoom.setObjectName("removeRoom")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.monthSelection = QComboBox(self.centralwidget)
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.addItem("")
        self.monthSelection.setObjectName("monthSelection")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.monthSelection.sizePolicy().hasHeightForWidth())
        self.monthSelection.setSizePolicy(sizePolicy1)
        self.monthSelection.setMinimumSize(QSize(120, 0))
        self.monthSelection.setMaxVisibleItems(12)

        self.gridLayout.addWidget(self.monthSelection, 0, 0, 1, 1)

        self.yearSelection = QDateEdit(self.centralwidget)
        self.yearSelection.setObjectName("yearSelection")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.yearSelection.sizePolicy().hasHeightForWidth())
        self.yearSelection.setSizePolicy(sizePolicy2)
        self.yearSelection.setMinimumSize(QSize(50, 0))
        self.yearSelection.setSizeIncrement(QSize(0, 0))
        self.yearSelection.setBaseSize(QSize(0, 0))
        self.yearSelection.setCurrentSection(QDateTimeEdit.YearSection)
        self.yearSelection.setCalendarPopup(False)
        self.yearSelection.setDate(QDate(2010, 1, 1))

        self.gridLayout.addWidget(self.yearSelection, 0, 1, 1, 1)

        self.roomTypeSelection = QComboBox(self.centralwidget)
        self.roomTypeSelection.addItem("")
        self.roomTypeSelection.setObjectName("roomTypeSelection")
        sizePolicy2.setHeightForWidth(self.roomTypeSelection.sizePolicy().hasHeightForWidth())
        self.roomTypeSelection.setSizePolicy(sizePolicy2)
        self.roomTypeSelection.setMinimumSize(QSize(100, 0))
        self.roomTypeSelection.setBaseSize(QSize(0, 0))

        self.gridLayout.addWidget(self.roomTypeSelection, 0, 2, 1, 1)

        self.showButton = QPushButton(self.centralwidget)
        self.showButton.setObjectName("showButton")
        sizePolicy2.setHeightForWidth(self.showButton.sizePolicy().hasHeightForWidth())
        self.showButton.setSizePolicy(sizePolicy2)

        self.gridLayout.addWidget(self.showButton, 0, 3, 1, 1)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout.addItem(self.horizontalSpacer, 0, 4, 1, 1)

        self.tableWidget = QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy3)
        self.tableWidget.setMinimumSize(QSize(1000, 0))
        self.tableWidget.setFrameShape(QFrame.StyledPanel)
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionMode(QAbstractItemView.NoSelection)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(Qt.SolidLine)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(45)
        self.tableWidget.verticalHeader().setStretchLastSection(False)

        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 7)

        self.deleteBooking = QPushButton(self.centralwidget)
        self.deleteBooking.setObjectName("deleteBooking")
        self.deleteBooking.setMinimumSize(QSize(200, 0))

        self.gridLayout.addWidget(self.deleteBooking, 2, 5, 1, 1)

        self.addBooking = QPushButton(self.centralwidget)
        self.addBooking.setObjectName("addBooking")
        sizePolicy4 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.addBooking.sizePolicy().hasHeightForWidth())
        self.addBooking.setSizePolicy(sizePolicy4)
        self.addBooking.setMinimumSize(QSize(200, 0))
        self.addBooking.setSizeIncrement(QSize(500, 0))
        self.addBooking.setBaseSize(QSize(0, 0))

        self.gridLayout.addWidget(self.addBooking, 2, 6, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        self.menubar.setGeometry(QRect(0, 0, 1114, 21))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menu.addAction(self.addRoom)
        self.menu.addAction(self.removeRoom)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", "\u039a\u03c1\u03b1\u03c4\u03ae\u03c3\u03b5\u03b9\u03c2", None))
        self.addRoom.setText(QCoreApplication.translate("MainWindow", "\u03a0\u03c1\u03bf\u03c3\u03b8\u03ae\u03ba\u03b7 \u0394\u03c9\u03bc\u03b1\u03c4\u03af\u03bf\u03c5", None))
        self.removeRoom.setText(QCoreApplication.translate("MainWindow", "\u0394\u03b9\u03b1\u03b3\u03c1\u03b1\u03c6\u03ae \u0394\u03c9\u03bc\u03b1\u03c4\u03af\u03bf\u03c5", None))
#if QT_CONFIG(tooltip)
        self.removeRoom.setToolTip(QCoreApplication.translate("MainWindow", "\u0394\u03b9\u03b1\u03b3\u03c1\u03b1\u03c6\u03ae \u0394\u03c9\u03bc\u03b1\u03c4\u03af\u03bf\u03c5", None))
#endif // QT_CONFIG(tooltip)
        self.monthSelection.setItemText(0, QCoreApplication.translate("MainWindow", "\u0399\u03b1\u03bd\u03bf\u03c5\u03ac\u03c1\u03b9\u03bf\u03c2", None))
        self.monthSelection.setItemText(1, QCoreApplication.translate("MainWindow", "\u03a6\u03b5\u03b2\u03c1\u03bf\u03c5\u03ac\u03c1\u03b9\u03bf\u03c2", None))
        self.monthSelection.setItemText(2, QCoreApplication.translate("MainWindow", "\u039c\u03ac\u03c1\u03c4\u03b9\u03bf\u03c2", None))
        self.monthSelection.setItemText(3, QCoreApplication.translate("MainWindow", "\u0391\u03c0\u03c1\u03af\u03bb\u03b9\u03bf\u03c2", None))
        self.monthSelection.setItemText(4, QCoreApplication.translate("MainWindow", "\u039c\u03ac\u03b9\u03bf\u03c2", None))
        self.monthSelection.setItemText(5, QCoreApplication.translate("MainWindow", "\u0399\u03bf\u03cd\u03bd\u03b9\u03bf\u03c2", None))
        self.monthSelection.setItemText(6, QCoreApplication.translate("MainWindow", "\u0399\u03bf\u03cd\u03bb\u03b9\u03bf\u03c2", None))
        self.monthSelection.setItemText(7, QCoreApplication.translate("MainWindow", "\u0391\u03cd\u03b3\u03bf\u03c5\u03c3\u03c4\u03bf\u03c2", None))
        self.monthSelection.setItemText(8, QCoreApplication.translate("MainWindow", "\u03a3\u03b5\u03c0\u03c4\u03ad\u03bc\u03b2\u03c1\u03b9\u03bf\u03c2", None))
        self.monthSelection.setItemText(9, QCoreApplication.translate("MainWindow", "\u039f\u03ba\u03c4\u03ce\u03b2\u03c1\u03b9\u03bf\u03c2", None))
        self.monthSelection.setItemText(10, QCoreApplication.translate("MainWindow", "\u039d\u03bf\u03ad\u03bc\u03b2\u03c1\u03b9\u03bf\u03c2", None))
        self.monthSelection.setItemText(11, QCoreApplication.translate("MainWindow", "\u0394\u03b5\u03ba\u03ad\u03bc\u03b2\u03c1\u03b9\u03bf\u03c2", None))

        self.yearSelection.setDisplayFormat(QCoreApplication.translate("MainWindow", "yyyy", None))
        self.roomTypeSelection.setItemText(0, QCoreApplication.translate("MainWindow", "\u038c\u03bb\u03b1", None))

#if QT_CONFIG(tooltip)
        self.showButton.setToolTip(QCoreApplication.translate("MainWindow", "\u0395\u03bc\u03c6\u03b1\u03bd\u03af\u03b6\u03b5\u03b9 \u03c4\u03b1 \u03b4\u03b5\u03b4\u03bf\u03bc\u03ad\u03bd\u03b1 \u03c0\u03b5\u03bb\u03b1\u03c4\u03ce\u03bd \u03b3\u03b9\u03b1 \u03c4\u03b7\u03bd \u03b5\u03c0\u03b9\u03bb\u03b5\u03b3\u03bc\u03ad\u03bd\u03b7 \u03b7\u03bc\u03b5\u03c1\u03bf\u03bc\u03b7\u03bd\u03af\u03b1", None))
#endif // QT_CONFIG(tooltip)
        self.showButton.setText(QCoreApplication.translate("MainWindow", "\u0395\u03bc\u03c6\u03ac\u03bd\u03b9\u03c3\u03b7", None))
#if QT_CONFIG(tooltip)
        self.tableWidget.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.deleteBooking.setText(QCoreApplication.translate("MainWindow", "\u0394\u03b9\u03b1\u03b3\u03c1\u03b1\u03c6\u03ae \u039a\u03c1\u03ac\u03c4\u03b7\u03c3\u03b7\u03c2", None))
        self.addBooking.setText(QCoreApplication.translate("MainWindow", "\u03a0\u03c1\u03bf\u03c3\u03b8\u03ae\u03ba\u03b7 \u039a\u03c1\u03ac\u03c4\u03b7\u03c3\u03b7\u03c2", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", "\u039c\u03b5\u03bd\u03bf\u03cd", None))
    # retranslateUi

